name: 检测论坛状态
run-name: 全部查活

on:
  schedule:
    - cron: "55 */6 * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - title: "MCBBS"
            url: "https://www.mcbbs.net"
          - title: "最MC"
            url: "http://www.zuimc.com"
          - title: "网易我的世界论坛"
            url: "https://mc.netease.com"
          - title: "MineBBS"
            url: "https://minebbs.com"
          - title: "九域资源社区"
            url: "https://bbs.mc9y.net"
          - title: "暮光方块论坛"
            url: "https://bbs.tsfk.top"
          - title: "像素点之家"
            url: "https://mcbar.club"
          - title: "小黑资源论坛"
            url: "https://www.blmcpia.com"
          - title: "苦力怕论坛"
            url: "https://klpbbs.com"
          - title: "深空Aurora"
            url: "https://bbs.aurora-sky.top"
          - title: "像素工坊"
            url: "https://www.pixelecraft.com"
          - title: "我的世界教育版中文论坛"
            url: "https://www.mceebbs.com"
          - title: "小僵尸论坛"
            url: "https://www.zitbbs.com"
          - title: "MCHVH"
            url: "https://mchvh.com"
          - title: "MCPPS"
            url: "https://mcpps.cn"
          - title: "我的世界UTC论坛"
            url: "https://bbs.mcutc.cn"
          - title: "MCraft BBS"
            url: "http://mcraftbbs.cn/"
          - title: "MineTalk"
            url: "https://www.minebox.store"
          - title: "像素世界论坛"
            url: "https://www.pixelbbs.cn"
          - title: "萝卜我的世界论坛"
            url: "https://www.luobomc.top"
          - title: "MC-BBS"
            url: "https://mc-bbs.net"
          - title: "MCSbbs"
            url: "https://mcsbbs.cn"
          - title: "美西螈论坛"
            url: "https://www.mcmxy.cn"
          - title: "SarBBS"
            url: "https://forum.sarskin.cn"
          - title: "DoMInecraftBBS"
            url: "https://www.domcbbs.cn"
          - title: "PiboPibo论坛"
            url: "https://www.pibopibo.com"
          - title: "Tinksp资源论坛"
            url: "https://www.tinksp.com"
          - title: "McFun"
            url: "https://www.mcshuo.com"
          - title: "末影论坛"
            url: "https://enderbbs.wavemoe.com"
          - title: "ikunmc"
            url: "https://www.ikunmc.com"
          - title: "SimpBBS"
            url: "https://www.simpbbs.com"
          - title: "HiMCBBS"
            url: "https://www.himcbbs.cn"
          - title: "方块社区"
            url: "https://www.mineforum.cn"
          - title: "MineSpeak论坛"
            url: "https://bbs.minesms.lol"
          - title: "画了个圈中文资源站"
            url: "https://imcbbs.com"
          - title: "CMCBBS"
            url: "https://www.cmcbbs.cn"
          - title: "MineFriend"
            url: "http://feiyutang.cn"
          - title: "neo社区"
            url: "https://mcneo.cn"
          - title: "SodaMC"
            url: "https://sodamc.com"
          - title: "MineMC我的世界中文资源论坛"
            url: "https://mc422.xyz"
          - title: "大家的世界"
            url: "https://bbs.mclqj.site"
          - title: "MINEBBS"
            url: "https://www.minebbs.cc"
          - title: "黑曜石论坛"
            url: "https://mcobs.fun"
          - title: "MCBBS 2nd"
            url: "https://mcbbs.app"
          - title: "potatobbs"
            url: "http://potato.eeeyt.cn"
          - title: "青草原MC社区"
            url: "https://qcymc.net"
          - title: "MineNets"
            url: "https://www.minenets.cn"
          - title: "MC中文资源站"
            url: "https://www.mcbbs.top"
          - title: "REMCBBS我的世界星幻论坛"
            url: "https://remcbbs.com"
          - title: "星辰论坛"
            url: "https://www.mcbbs.website"
          - title: "新世界中文论坛"
            url: "https://nwbbs.cn"
          - title: "MC星空社"
            url: "https://www.ufacai.top"
          - title: "BetaMC"
            url: "https://www.betamc.net"
          - title: "土豆社区"
            url: "https://bbs2.potatokj.top"
          - title: "MCBBS 3rd"
            url: "https://mcbbs.asia"
          - title: "MCBBS 4th"
            url: "https://www.mcbbs.lol"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet tool install Web.Ping -g
      - name: Ping ${{ matrix.title }}
        run: Web.Ping --host ${{ matrix.url }}
